#workflow_name: test-trivy-scan.yml
name: trivy-scan

on:
  workflow_dispatch:
  push:
jobs:
  trivy-scan:
    uses: bruce-wh-li/devsecops-tools/.github/workflows/trivy-container.yaml@main
    with:
# Docker Url you want to save image
#      IMAGE: <docker account>/bcgov-nginx-demo
      IMAGE: brucecruise/bcgov_nginx-demo
      TAG: latest



