#workflow_name: test-trivy-scan.yml
name: trivy-scan
on:
  workflow_dispatch:
  push:


jobs:
  trivy-scan:
    uses: bruce-wh-li/devsecops-tools/.github/workflows/trivy-container.yaml@main
    with:
# Docker Url you want to save image
#      IMAGE: <docker account>/bcgov-nginx-demo
      IMAGE: ${{env.image_name}}/bcgov-nginx-demo
      TAG: latest
    secrets:
      image_name: ${{ secrets.IMAGE_REGISTRY_USER}}
    env:
      image_name: ${{ secrets.IMAGE_REGISTRY_USER}}



