#workflow_name: test-docker-build-push.yml
name: docker-build-push
on:
  workflow_dispatch:
  push:
jobs:
  build-push:
    uses: bruce-wh-li/devsecops-tools/.github/workflows/build-push.yaml@main
    with:
      IMAGE_REGISTRY: docker.io
# your docker image url      
# example, IMAGE: gregnrobinson/bcgov-nginx-demo
#     IMAGE: <docker hub account>/bcgov-nginx-demo
      IMAGE: brucecruise/bcgov_nginx-demo
      WORKDIR: ./demo/nginx
    secrets:
     IMAGE_REGISTRY_USER: ${{ secrets.IMAGE_REGISTRY_USER }}
     IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}   
